apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 2  # Number of nginx instances (pods) you want to run
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: docker.io/tuhin200/tuhin-cv:13
        ports:
        - containerPort: 80  # Expose port 80 inside the container
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 30080        # Port inside the cluster
      targetPort: 80     # Port inside the container
      nodePort: 30080    # Explicitly specify the external port (Optional, can be auto-assigned)
  type: NodePort        # Exposing the service as a NodePort
